# Site settings
title: Chris Joy
description: Chris Joy's personal website. Chris is a level 7 student of the internet, lurking around the interwebs, discovering dank memes and investment strategies.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
paginate: 5
permalink: /:title/
include: ['_pages']
future: true
markdown: kramdown
# Build settings
plugins: [jekyll-paginate, kramdown, jekyll-seo-tag, jekyll-sitemap]

collections:
  _notes:
    output: true
    permalink: /notes/:title/
  _posts:
    output: true
    permalink: /:title/
  _projects:
    output: true
    permalink: /projects/:title/