# Site settings
title: Chris Joy
email: chrisjoy@protonmail.com
description: Chris Joy's personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
twitter_username: mrchrisjoy
github_username:  mrchrisjoy
instagram_username: mrchrisjoy
paginate: 5
permalink: /:categories/:title/

future: true
plugins: [jekyll-paginate, kramdown, jekyll-seo-tag, jekyll-sitemap]
# Build settings
markdown: kramdown

collections:
  notes:
    output: true
    permalink: /:categories/:title/