# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Joy
email: chrisjoy@protonmail.com
description: Chris Joy's personal website. Exploring social, economic, mathematical and computational frameworks for the advancement of civilisation.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
twitter_username: mrchrisjoy
github_username:  mrchrisjoy
instagram_username: mrchrisjoy
paginate: 5
permalink: /:categories/:title/

future: true
gems: [jekyll-paginate, kramdown, jekyll-seo-tag, jekyll-sitemap]
# Build settings
markdown: kramdown

collections:
  notes:
    output: true
    permalink: /:categories/:title/
