# Site settings
title: Chris Joy
email: chrisjoy@protonmail.com
description: Chris Joy's personal website.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
twitter_username: mrchrisjoy
github_username:  mrchrisjoy
instagram_username: mrchrisjoy
paginate: 5
permalink: /:title/
include: ['_pages']
future: true
markdown: kramdown
# Build settings
plugins: [jekyll-paginate, kramdown, jekyll-seo-tag, jekyll-sitemap]

collections:
  notes:
    output: true